# Generated by Django 4.2.23 on 2025-07-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_conversation_message_conversation_conv_id_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_hash',
        ),
    ]
